### ISSUE TITLE
Jetty can't parse starting port

### ISSUE THREAD

**Issue by chumaltd** [gitbucket/gitbucket-docker#20]
Hi, I got errors at startup as bellows.

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "tcp://10.27.241.91:80"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at JettyLauncher.getPort(JettyLauncher.java:165)
	at JettyLauncher.main(JettyLauncher.java:74)
```

I took gitbucket/gitbucket:4 image, running on Google Kubernetes Engine.

https://hub.docker.com/layers/gitbucket/gitbucket/4/images/sha256-65254a12c188aa9067ddab7ecba6eacb149fc4e15a12295200761295a8e4ac86?context=explore

So, I filled with "--port=8080" command line option, and it works.
I don't know what is suitable for default option, but some environment may need default port settings.

**Comment by chumaltd** [comment]
I think setting `GITBUCKET_PORT` env explicitly is a handy way.
For k8s users, an partial example looks like:

```yaml
kind: StatefulSet
spec:
  template:
    spec:
      containers:
      - name: gitbucket
        env:
        - name: GITBUCKET_PORT
          value: 8080
```

Other env listed in [Basic configurations](https://github.com/gitbucket/gitbucket/wiki/Basic-configurations)  should also work.  
k8s users are growing, so the official docker doc is nice to have a starter description.
